/*
 * MIT License
 *
 * Copyright (c) 2021 OroArmor (Eli Orona)
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

package com.oroarmor.discordbot;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.List;
import java.util.concurrent.TimeUnit;
import java.util.stream.StreamSupport;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.json.JsonMapper;
import com.fasterxml.jackson.databind.node.ArrayNode;
import com.oroarmor.discordbot.commands.*;
import com.oroarmor.discordbot.versions.VersionHandler;


import net.dv8tion.jda.api.JDA;
import net.dv8tion.jda.api.JDABuilder;
import net.dv8tion.jda.api.entities.Role;
import net.dv8tion.jda.api.entities.channel.concrete.TextChannel;
import net.dv8tion.jda.api.events.message.MessageReceivedEvent;
import net.dv8tion.jda.api.events.message.react.MessageReactionAddEvent;
import net.dv8tion.jda.api.events.session.ReadyEvent;
import net.dv8tion.jda.api.hooks.ListenerAdapter;
import net.dv8tion.jda.api.requests.GatewayIntent;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class DiscordBot {
    public static boolean locked;
    public static TextChannel logChannel;

    public static final Path RUN_DIRECTORY = Paths.get("run");
    public static final Path CACHE_DIRECTORY = RUN_DIRECTORY.resolve("cache");
    public static final Path CONFIGURATION_FILE = RUN_DIRECTORY.resolve("configuration.json");

    private static Thread checkerThread;

    public static void main(String[] args)
            throws InterruptedException {
        // Note: It is important to register your ReadyListener before building
        JDA jda = JDABuilder.createDefault(System.getenv("BOT_TOKEN"))
                .enableIntents(GatewayIntent.DIRECT_MESSAGES, GatewayIntent.GUILD_MESSAGES, GatewayIntent.MESSAGE_CONTENT, GatewayIntent.GUILD_MESSAGE_REACTIONS)
                .addEventListeners(new EventListener())
                .build();

        if (System.getenv("DEBUG") != null) {
            CommandManager.addCommand(new PingCommand());
        }

        CommandManager.addCommand(new AliasesCommand());
        CommandManager.addCommand(new ChangePrefixCommand());
        CommandManager.addCommand(new CommandsCommand());
        CommandManager.addCommand(new EmbedCommand("fabric-api", "Info about the fabric api.", Permissions.ANY, "Fabric API", 0xfcd98d, "Netherite Plus Fabric requires the fabric api to run. Download it from: https://www.curseforge.com/minecraft/mc-mods/fabric-api."));
        CommandManager.addCommand(new FaqCommand());
        CommandManager.addCommand(new IssueCommand());
        CommandManager.addCommand(new LinkCommand("CurseForge", "https://www.curseforge.com/members/oroarmor/projects", 0x6441A4));
        CommandManager.addCommand(new LinkCommand("Github", "https://github.com/OroArmor", 0x555555));
        CommandManager.addCommand(new LinkCommand("Modrinth", "https://modrinth.com/user/h74rYEcI", 0x079515));
        CommandManager.addCommand(new LinkCommand("Patreon", "https://patreon.com/oroarmor", 0xFF6871));
        CommandManager.addCommand(new LinkCommand("Youtube", "https://www.youtube.com/channel/UCsbVQJhwgXIJ035XUCN9IRw", 0xff0000));
        CommandManager.addCommand(new ModCommand());
        CommandManager.addCommand(new ModsCommand());
        CommandManager.addCommand(new RefreshModsCommand());
        CommandManager.addCommand(new StringCommand("apply-for-mod", "Provides the link to the moderator application page.", Permissions.ANY, "Apply for moderator at: https://forms.gle/F4LPDH7xD96VknY39"));
        CommandManager.addCommand(new LockServerCommand());
        CommandManager.addCommand(new ReloadCommand());
        if (System.getenv("WOL_MAC") != null) {
            CommandManager.addCommand(new ShellCommand("wol", "Wake up OroArmor's Computer", new String[]{"wakeonlan", System.getenv("WOL_MAC")}));
        }


        CommandManager.addAlias("alias", "aliases");
        CommandManager.addAlias("cf", "curseforge");
        CommandManager.addAlias("command", "commands");
        CommandManager.addAlias("fapi", "fabric-api");
        CommandManager.addAlias("gh", "github");
        CommandManager.addAlias("yt", "youtube");

        // optionally block until JDA is ready
        jda.awaitReady();
    }

    public static void load(JDA jda) {
        try {
            JsonNode json = new JsonMapper().readTree(Files.newBufferedReader(CONFIGURATION_FILE));

            logChannel = jda.getTextChannelById(json.get("log_channel").asLong());

            List<TextChannel> updateChannelIds = StreamSupport.stream(json.get("update_channel_ids").spliterator(), false)
                    .mapToLong(JsonNode::asLong)
                    .mapToObj(jda::getTextChannelById)
                    .toList();

            List<VersionHandler.VersionChecker> checkers = VersionHandler.loadFromJson(((ArrayNode) json.get("checkers")));

            VersionHandler handler = new VersionHandler(updateChannelIds, checkers);

            if (checkerThread != null) {
                checkerThread.interrupt();
            }

            checkerThread = new Thread(() -> {
                while (true) {
                    handler.update();
                    try {
                        TimeUnit.MINUTES.sleep(10);
                    } catch (InterruptedException ignored) {
                        break;
                    }
                }
            });

            checkerThread.start();

        } catch (IOException e) {
            throw new RuntimeException(e);
        }
    }

    public static class EventListener extends ListenerAdapter {
        public void onMessageReceived(MessageReceivedEvent event) {
            if (event.getMessage().getContentRaw().equals("o/") && event.getAuthor() != event.getJDA().getSelfUser() && event.getChannel().getName().equals("general-chat")) {
                event.getChannel().sendMessage("o/").queue();
            }
            CommandManager.runCommand(event.getMember(), event.getChannel(), event.getMessage());
        }

        @Override
        public void onMessageReactionAdd(MessageReactionAddEvent event) {
            if (event.getChannel().getName().equals("rules")) {
                if (!locked) {
                    Role role = event.getGuild().getRoles().stream().filter(role1 -> role1.getName().equals("Mod Lover")).findFirst().orElse(null);
                    if (role == null || event.getMember() == null) {
                        return;
                    }
                    event.getGuild().addRoleToMember(event.getMember(), role).queue();
                } else {
                    event.getReaction().removeReaction(event.getMember().getUser()).queue();
                    event.getMember().getUser().openPrivateChannel().queue(privateChannel -> {
                        privateChannel.sendMessage("OroArmor's server is locked. Please try again later.").queue();
                    });
                    logChannel.sendMessage("Prevented user <@" + event.getUserId() + "> from joining.").queue();
                }
            }
        }

        @Override
        public void onReady(ReadyEvent event) {
            System.out.println("Logged in!");

            load(event.getJDA());
        }
    }
}

